### ISSUE TITLE
clang::Type::num_template_args should return Option<u32>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#135]
Right now it returns -1 if the type is not a class template specialization. We should check for this case and return `None`, otherwise `Some`. This will be one less foot gun for callers of this method.

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga13f25981892e38c345d609b56ae1ee9c

> -1 if type T is not a class template specialization.

I can mentor whoever would like to work on this.

**Comment by jeanphilippeD** [comment]
Hi, I'll be happy to take this one.

**Comment by jeanphilippeD** [comment]
Hello,
I have a question regarding this change:

This function used to return a signed 'c_int' (i32).
Was it the intention to convert it to an unsigned u32: Option<u32> instead of using Option<c_int>?

If so, how should be best handle calling clang::Type::template_arg_type?
 - should we use template_arg_type(i as i32)?
 - should we change the interface of template_arg_type to take u32 and convert in the implementation?

**Comment by emilio** [comment]
That sounds right, in general, it makes sense to return an `Option<u32>`, since if there are template arguments the number is going to be unsigned.

It also makes sense for `template_arg_type` to get an unsigned integer, so I'm fine to convert it inside that function to what libclang expects.
