### ISSUE TITLE
Generate layout tests for template specializations.

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#57]
Right now we don't generate layout tests for types with template parameters for obvious reasons. The bindgen rewrite tracks all the template specializations, so we can start generating layout tests for them.

**Comment by impowski** [comment]
I can take it but can you guide me through?

**Comment by emilio** [comment]
Sure, thanks for doing it!

Mainly we don't generate any code in `codegen/mod.rs` for template specializations, instead we just return:

```rust
        if self.has_non_type_template_params() ||
           self.is_template_specialization() {
            return;
        }
```

In the template specialization case, it should be easy to reuse the logic inside `if applicable_template_args.is_empty() && !self.found_unknown_attr()` to generate the same kind of `#[test]` functions for these.

Let me know if you need more help, thanks for tackling this! :)

**Comment by impowski** [comment]
@emilio Just to make it clear where do I need to put this `#[test]` functions inside of `codegen/mod.rs`?

**Comment by impowski** [comment]
@emilio So I started working on it and trying to understand it little bit better. So right now when I run `.hpp` file with something like this:
```
template<typename T>
class Template
{
  T key;
  T data;
  void f();
};

template<>
void Template<int>::f();
```
It's generates this:
```
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Template<T> {
    pub key: T,
    pub data: T,
}
#[test]
fn bindgen_test_layout_template_Template() {
    assert_eq!(::std::mem::size_of::<Template>() , 8usize);
    assert_eq!(::std::mem::align_of::<Template>() , 4usize);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Template<int> {
    pub _phantom_0: ::std::marker::PhantomData<int>,
}
extern "C" {
    pub fn f(this: *mut Template<::std::os::raw::c_int>);
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Rooted {
    pub ptr: ::std::os::raw::c_int,
}
```
And right now I'm just trying to understand where I need to move next maybe I need to change something because I was playing around with `self.template_args()`. So give me some info about these tests and how they should look. And I still thiking that I don't need to put `methods` and other things which was used around `if applicable_template_args.is_empty() && !self.found_unknown_attr()`.

**Comment by impowski** [comment]
@emilio Please close this issue.
