### ISSUE TITLE
Struct and function name collision

### ISSUE THREAD

**Issue by rpjohnst** [servo/rust-bindgen#654]
Bindgen represents a forward-declared C struct as a tuple struct of a 0-sized array. This leads to naming collisions when the C code has a function of the same name. IIUC, this isn't strictly required as Rust has separate type and function namespaces- tuple structs just have a representation in both.

### Input C/C++ Header

```C++
struct foo;
extern "C" int foo(void);
```

### Bindgen Invokation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .generate()
    .unwrap()
```

### Actual Results

```
error[E0428]: a value named `foo` has already been defined in this module
   |
9  |     pub struct foo([u8; 0]);
   |     ------------------------ previous definition of `foo` here
10 |     extern "C" {
11 |         pub fn foo() -> ::ctypes::c_int;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `foo` already defined
```

**Comment by emilio** [comment]
Yes, this is known, and it's one of these awkward convenience and difference in naming between C and C++... This is actually pretty similar to #647 in practice, where a system to rename structs and functions is proposed.

Perhaps we could special-case top-level functions, since they cannot be referenced from other types, and just deduplicate their names when appropriate, using `#[link_name]`. Or even move all top-level functions to their own module?

What do you think @fitzgen?

**Comment by rpjohnst** [comment]
What I was getting at by mentioning tuple structs in particular is that non-tuple structs don't have this name collision. For example, this works:

    struct foo { foo: [u8; 0], }
    extern "C" { fn foo(); }

**Comment by emilio** [comment]
Hmm... I see, good point. Perhaps we could just change how we generate opaque types to avoid this.
