### ISSUE TITLE
Get CI working with libclang 4.0

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#697]
With #696 and #694, we should be able to pass tests in libclang 4.0.

There are a few tests which are expected to have different output in this clang version, mentioned in #696.

We have right now in our headers a `// bindgen-unstable` annotation, that basically avoids running tests depending on a feature, which we enable depending on the LLVM version in CI. We'd need to extend/refactor this in order to support multiple expectation files per platform.

One alternative is using a subdirectory, something like:

 * tests/expectations/tests/3.8/foo.rs
 * tests/expectations/tests/3.9/foo.rs

And so on.

Other alternative is just using name suffixes:

 * tests/expectations/tests/foo-3.8.rs
 * ...

When that's done, we need to setup CI for libclang 4.0, which is probably just a matter of removing the relevant line from the [`allow_failures`](/servo/rust-bindgen/blob/master/.travis.yml#L27) section.

**Comment by fitzgen** [comment]
Thanks for laying this out, @emilio!

I prefer subdirectories to suffixes for different test expectations across different libclang versions.

Once libclang 4.0 is passing in CI, we should look at testing (and allowing failures?) of libclang 5.0 tip.

Additionally, once we have the infrastructure to allow different libclangs to have different test expectations, we can also turn on CI for libclang 3.7 (and even 3.6?).

Because updating test expectations will be harder (will require wrangling multiple libclang versions), we must ensure that our diff printing behavior when actual emitted bindings != expected emitted bindings is preserved. This allows one to update test expectations even when one doesn't have the particular libclang version handy. We should describe this process in CONTRIBUTNG.md.
